# Generated by Django 5.0.4 on 2024-04-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='refreshstore',
        ),
    ]
